modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="fargos"
version="1.7.0"
displayName="Fargo's Mod"
logoFile="icon.png"
authors="STS15, ADRMLParangosky, and Sassidy"
#displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description='''
Fargo's mod includes multiple unique enchantment curios and a couple interesting boss fights
'''

[[dependencies.fargos]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.fargos]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.fargos]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.4.3,)"

[[mixins]]
    refmap="fargos-refmap.json"
    config="fargos.mixins.json"
